image:
  - Visual Studio 2017

platform:
  - x64

environment:
  CONFIG: Release
  CRT_LINKAGE: dynamic
  LIBRARY_LINKAGE: static
  CTEST_OUTPUT_ON_FAILURE: 1

  matrix:
    - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      TARGET_ARCHITECTURE: x64
      QT_BUILD: msvc2017_64

init:
  - cmake --version
  - msbuild /version
  - set "PATH=C:\Qt\5.11\%QT_BUILD%\bin;%PATH%"

install:
  - cd C:\Tools\vcpkg
  - git config user.name "Spix Appveyor"
  - git config user.email "appveyor@somewhere"
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%

  - echo set(VCPKG_TARGET_ARCHITECTURE %TARGET_ARCHITECTURE%) > C:\tools\vcpkg\triplets\custom-triplet.cmake
  - echo set(VCPKG_CRT_LINKAGE %CRT_LINKAGE%) >> C:\tools\vcpkg\triplets\custom-triplet.cmake
  - echo set(VCPKG_LIBRARY_LINKAGE %LIBRARY_LINKAGE%) >> C:\tools\vcpkg\triplets\custom-triplet.cmake
  - cat C:\tools\vcpkg\triplets\custom-triplet.cmake

  - vcpkg install
      gtest
      anyrpc
      --triplet custom-triplet

#build_script:
#  - mkdir build
#  - cd build
#  - cmake .. -G "%CMAKE_GENERATOR%" -DSPIX_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=%CONFIG% -DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=custom-triplet
#  - cmake --build . --config %CONFIG%

#test_script:
#  - cmake --build . --target RUN_TESTS --config %CONFIG%
